#
# Fuel Bar and Speed will be displayed in the following default format:
# "[{fuelbars}] | {speed} b/s"
#
# Formats:
# Colors: &7
# RGB: &x&r&r&g&g&b&b
#
# Placeholders:
# {fuelbars}
# {speed}
#

Config:
  # Design your own Fuelbar!
  fuelbarDesign: '&8[{fuelbars}&8] &8| {speed} &x&f&f&c&5&4&fb&8/&x&f&f&c&5&4&fs'
  
  # Design your own Fuelbar!
  speedOnlyBar: '{speed} &x&f&f&c&5&4&fb&8/&x&f&f&c&5&4&fs'
  
  # Colors for the available {fuelbars}
  fuelLeftColor: '&x&f&f&c&5&4&f'
  
  # Colors for the empty {fuelbars}
  fuelSpentColor: '&7'
  
  # Color for the {speed}
  speedColor: '&x&f&f&c&5&4&f'
  
  # Amount of Bars
  barAmount: 30
  
  # Bar Symbol
  barSymbol: '|'